# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Sum the elements of a matrix
#' @description Sum the elements of a matrix
#' @param X A matrix
#' @return The sum of the elements of the matrix
#' @examples
#' X <- matrix(1:10, 2, 5)
#' sum_matrix(X)
sum_matrix <- function(X, n_threads = 4L) {
    .Call(`_toyPackage_sum_matrix`, X, n_threads)
}

